/** Whether the client is looking to purchase ('buyer') or list a property ('seller'). */
export type ClientType = 'buyer' | 'seller'

/** The client's current engagement status with the realtor. */
export type ClientStatus = 'active' | 'inactive' | 'closed'

/** The client's position in the sales pipeline, rendered as Kanban columns. */
export type ClientStage =
  | 'lead'
  | 'contacted'
  | 'showing'
  | 'negotiation'
  | 'closed'
  | 'lost'

/** The financing method the client intends to use for the transaction. */
export type SaleType = 'cash' | 'loan'

/** The category of property the client is interested in. Maps to the DB enum. */
export type PropertyType = 'house' | 'condo' | 'apartment' | 'land' | 'commercial'

/** Mirrors the `clients` table row. Fields from budget_min down are buyer-specific and null for sellers. */
export interface Client {
  id: string
  realtor_id: string
  client_type: ClientType
  status: ClientStatus
  stage: ClientStage
  name: string
  email: string | null
  phone: string | null
  notes: string | null
  budget_min: number | null
  budget_max: number | null
  preferred_locations: string[] | null  // stored as a Postgres text[] array
  property_types: PropertyType[] | null // stored as a Postgres text[] array
  sale_type: SaleType | null
  bedrooms_min: number | null
  bedrooms_max: number | null
  bathrooms_min: number | null
  bathrooms_max: number | null
  created_at: string
  updated_at: string
}

/** Shape for inserting a new client row; id and timestamps are generated by the database. */
export type ClientInsert = Omit<Client, 'id' | 'created_at' | 'updated_at'>

/** Shape for updating an existing client row; id, realtor_id, and timestamps are immutable. */
export type ClientUpdate = Partial<Omit<Client, 'id' | 'realtor_id' | 'created_at' | 'updated_at'>>
