/**
 * A custom, realtor-authored email template stored in the `email_templates` table.
 * Predefined templates share the same shape but are declared in code
 * (lib/email/templates.ts) and are not persisted.
 */
export interface EmailTemplate {
  id: string
  realtor_id: string
  name: string
  subject: string
  body: string
  created_at: string
  updated_at: string
}

/** Shape for inserting a new template row; id and timestamps are generated by the database. */
export type EmailTemplateInsert = Omit<
  EmailTemplate,
  'id' | 'created_at' | 'updated_at'
>

/**
 * A template ready to be presented in a picker. Predefined templates use a
 * synthetic string id (e.g. "predefined:open-house") and carry `predefined: true`
 * so the UI can prevent editing/deleting them.
 */
export interface PickableTemplate {
  id: string
  name: string
  subject: string
  body: string
  predefined: boolean
}
